version: '3.4'

services:
  everbridge.controlcenter.technicalchallenge:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - USE_DEVELOPMENT_SERVER=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    build:    
      args:
        buildConfiguration: debug